name: start cimon


on: pull_request_target


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
          log-level: debug


      - name: run
        run: |
          curl -vvv https://api.github.com/repos/elad-pticha/testing -H "Authorization: Bearer ${{ github.token }}"
